<div id="highlighted">
			<div class="container">
				<div class="header">
					<h2 class="page-title">
						<span>Photo galleries</span>
						<small>Checkout our photo galleries</small>
					</h2>
				</div>
			</div>
		</div>
		<div id="content">
			<div class="container portfolio">
				<!--Portfolio items-->
				<ul class="thumbnails row block projects" id="quicksand">
					<li class="col-md-4 print" data-id="1" data-type="print">
						<div class="">
							<div class="project">
								<a class="lnk-polaroid" href="#url-to-photo-gallery1">
									<img src="uploads/photo-galleries/1.jpg" alt="Photo Gallery 1 Title" class="img-polaroid img-responsive" />
								</a>
								<h3 class="title">
									<a href="#url-to-photo-gallery1">Photo Gallery 1 Title</a>
								</h3>
								<p class="muted">Gallery 1 Description</p>
							</div>
						</div>
					</li>
					<li class="col-md-4 print" data-id="2" data-type="print">
						<div class="">
							<div class="project">
								<a class="lnk-polaroid" href="#url-to-photo-gallery2">
									<img src="uploads/photo-galleries/2.jpg" alt="Photo Gallery 2 Title" class="img-polaroid img-responsive" />
								</a>
								<h3 class="title">
									<a href="#url-to-photo-gallery2">Photo Gallery 2 Title</a>
								</h3>
								<p class="muted">Gallery 2 Description</p>
							</div>
						</div>
					</li>
				</ul>
			</div>
		</div>