

    <!-- ======== @Region: #highlighted ======== -->
    <div id="highlighted">
        <!-- Flexslider - May use standard Bootstrap markup within slides - For best results use images all the same size (in this example they are 600px x 400px) -->
        <!--Flexslider Showshow-->
        <section class="flexslider-wrapper container">
            <div class="flexslider" id="index-slider">
                <!--The Slides-->
                <div class="slides">
                    
                    <?php foreach ($this->indexSlides as $indexSlide) { ?>
                        <div class="slide">
                            <div class="row">
                                <div class="col-sm-6">
                                    <img src="<?php echo $this->indexSlideImgUrl($indexSlide); ?>" alt="<?php echo $this->escape($indexSlide['title']); ?>" class="animated fadeInDownBig" />
                                </div>
                                <div class="col-sm-6 caption animated fadeInUpBig">
                                    <h2>
                                        <?php echo $this->escape($indexSlide['title']); ?>
                                    </h2>
                                    <p>
                                        <?php echo $this->escape($indexSlide['description']); ?>
                                    </p>
                                    <?php if ($indexSlide['link_type'] != 'NoLink') { 
                                        
                                        switch ($indexSlide['link_type']) {

                                                case 'SitemapPage':
                                                    ?> 
                                                        <a href="<?php echo $this->escape($this->sitemapPageUrl($indexSlide['sitemap_page_id'])); ?>" class="btn btn-lg btn-primary"><?php echo $this->escape($indexSlide['link_label']); ?></a>
                                                    <?php
                                                    break;
                                                case 'ExternalLink':
                                                    ?> 
                                                        <a href="<?php echo $this->escape($indexSlide['external_link_url']); ?>" class="btn btn-lg btn-primary" target="_blank"><?php echo $this->escape($indexSlide['link_label']); ?></a>
                                                    <?php
                                                    break;
                                                case 'InternalLink':
                                                    ?> 
                                                        <a href="<?php echo $this->escape($indexSlide['internal_link_url']); ?>" class="btn btn-lg btn-primary"><?php echo $this->escape($indexSlide['link_label']); ?></a>
                                                    <?php
                                                    break;
                                                default:
                                                    break;
                                        } ?>
                                        
                                    
                                    <?php } ?>
                                    
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                    
     

                </div>
            </div>
        </section>
    </div>

    <!-- ======== @Region: #content ======== -->
    <div id="content">
        <div class="container">
            <!-- Services -->
            <div class="block services margin-top-large">
                <h2 class="block-title">
                    <span>Our Services</span> 
                    <small><a href="/services">View all</a></small>
                </h2>
                <ul class="thumbnails row">
                    
                    <?php
                        //stavljen je limit na 4 moze i bez prelamanja
                        $i = 0;
                        foreach ($this->services as $service) {
                            if($i % 4 === 0) { // kraj reda i prelazak u novi ?>  
                                    </ul>
                                </div>

                                <div class="block services margin-top-large">
                                    <ul class="thumbnails row">
                            <?php }
                            $i++;
                            ?>
                            <li class="col-sm-3">
                                <h3 class="title">
                                    <i class=" <?php echo $this->escape($service['icon']); ?> "></i> <?php echo $this->escape($service['title']); ?>
                                </h3>
                                <p> <?php echo $this->escape($service['description']); ?> </p>
                            </li>              
                    <?php } ?>
                  
                </ul>
            </div>
            <!-- portfolio -->
            <!-- Recommended screenshot size: 400px x 300px -->
            <div class="block portfolio margin-top-large">
                <h2 class="block-title">
                    <span>Photo galleries</span> 
                    <small><a href="<?php echo $this->servicesPage; ?>">View all</a></small>
                </h2>
                <ul class="thumbnails row projects">
                    <li class="col-md-4 ">
                        <div class="">
                            <div class="project">
                                <a class="lnk-polaroid" href="#link-to-photo-gallery-1">
                                    <img src="/uploads/photo-galleries/1.jpg" alt="Photo Gallery 1 Title" class="img-polaroid img-responsive" />
                                </a>
                                <h3 class="title">
                                    <a href="#link-to-photo-gallery-1">Photo Gallery 1 Title</a>
                                    <small class="pull-right"></small>
                                </h3>
                                <p class="muted">Photo Gallery 1 Description</p>
                            </div>
                        </div>
                    </li>
                    <li class="col-md-4 ">
                        <div class="">
                            <div class="project">
                                <a class="lnk-polaroid" href="#link-to-photo-gallery-2">
                                    <img src="/uploads/photo-galleries/2.jpg" alt="Photo Gallery 2 Title" class="img-polaroid img-responsive" />
                                </a>
                                <h3 class="title">
                                    <a href="#link-to-photo-gallery-2">Photo Gallery 2 Title</a>
                                    <small class="pull-right"></small>
                                </h3>
                                <p class="muted">Photo Gallery 2 Description</p>
                            </div>
                        </div>
                    </li>
                    <li class="col-md-4 ">
                        <div class="">
                            <div class="project">
                                <a class="lnk-polaroid" href="#link-to-photo-gallery-3">
                                    <img src="/uploads/photo-galleries/3.jpg" alt="Photo Gallery 3 Title" class="img-polaroid img-responsive" />
                                </a>
                                <h3 class="title">
                                    <a href="#link-to-photo-gallery-3">Photo Gallery 3 Title</a>
                                    <small class="pull-right"></small>
                                </h3>
                                <p class="muted">Photo Gallery 3 Description</p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    
<?php
    $this->headLink()->appendStylesheet($this->baseUrl('/plugins/flexslider/flexslider.css'));
    $this->inlineScript()->appendFile($this->baseUrl('/plugins/flexslider/jquery.flexslider-min.js'));
?>
    
<script>
    <?php $this->inlineScript()->captureStart(); ?>
        
        $('#index-slider').flexslider({
            animation: 'slide',
            selector: '.slides > .slide',
            controlNav: true,
            smoothHeight: true,
            animationLoop: true,
            randomize: false
        });
        
    <?php $this->inlineScript()->captureEnd(); ?>
</script>