		<div id="highlighted">
			<div class="container">
				<div class="header">
					<h2 class="page-title">
						<span>Photo gallery</span>
					</h2>
					<a href="#link-to-all-galleries" class="btn btn-xs btn-default back-link"><i class="fa fa-arrow-left"></i> Back to all photo galleries</a>
				</div>
			</div>
		</div>
		<div id="content">
			<div class="container portfolio">
				<!--Portfolio feature item-->
				<div class="row">
					<div class="col-md-7 project-photos">
						<!-- Slider for project pictures -->
						<div id="photo-gallery-slider-id" class="carousel slide">
							<div class="carousel-inner">
								<div class="item active">
									<img src="uploads/photo-galleries/photos/1.jpg" alt="Photo 1 Title" />
									<div class="carousel-caption">
										<h4>
											Photo 1 Title
										</h4>
										<p>Photo 1 Description</p>
									</div>
								</div>
								<div class="item">
									<img src="uploads/photo-galleries/photos/2.jpg" alt="Photo 2 Title" />
									<div class="carousel-caption">
										<h4>
											Photo 2 Title
										</h4>
										<p>Photo 2 Description</p>
									</div>
								</div>
								<div class="item">
									<img src="uploads/photo-galleries/photos/3.jpg" alt="Photo 3 Title" />
									<div class="carousel-caption">
										<h4>
											Photo 3 Title
										</h4>
										<p>Photo 3 Description</p>
									</div>
								</div>
							</div>
							<a class="left carousel-control" href="#photo-gallery-slider-id" data-slide="prev">&lsaquo;</a> <a class="right carousel-control" href="#photo-gallery-slider-id" data-slide="next">&rsaquo;</a> 
						</div>
					</div>
					<div class="col-md-5 sidebar sidebar-right">
						<!-- quick details -->
						<div class="block">
							<h3 class="block-title">
								<span>Enkel Bootstraps Theme</span>
							</h3>
							<div class="block">
								<p>Elit pellentesque dolor facilisis aenean eu tempor, phasellus lundium risus dolor, augue, ridiculus nascetur odio ridiculus? Hac ac, adipiscing ut dapibus. Adipiscing cras in? Magna nisi augue odio! Pellentesque magnis? Lacus integer magnis purus sed mus lorem aliquam lectus, placerat pellentesque quis, nunc urna turpis lorem. Etiam velit, augue sed magnis placerat! In cras, dignissim lorem, porttitor in velit in, nisi vut a cursus cum, odio sagittis nisi turpis? Mus penatibus non, pulvinar porttitor arcu hac ut et ac integer? Ultricies est etiam sit. Urna ridiculus facilisis pulvinar, ultrices augue? Parturient velit non tincidunt sit sagittis pulvinar phasellus rhoncus hac! Sit porta. Tristique, hac. Porttitor adipiscing ac. Ac tincidunt a porttitor natoque auctor ultricies! Proin nunc scelerisque? Habitasse adipiscing? Cursus.</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>