<?php
    $this->headTitle('Contact');
?>


<div id="highlighted">
    <div class="container">
        <div class="header">
            <h2 class="page-title">
                <br>
                <span>Ask member: <?php echo $this->member['first_name'] . ' ' . $this->member['last_name']; ?></span> 
                
            </h2>
            <a href="#" class="thumbnail"  >
                <img src="<?php echo $this->memberImgUrl($this->member); ?>">
            </a>
        </div>
        
    </div>
</div>
<div id="content">
    <div class="container">
        <div class="block">
            <div class="row">
                <div class="col-sm-6">
                    <h3 class="block-title sub-title">
                        <span>Contact via message</span>
                    </h3>
                    <form action="#" id="contact-form">
                        <div class="form-group">
                            <input type="text" placeholder="Name" class="form-control">
                        </div>
                        <div class="form-group">
                            <input type="email" placeholder="Email" class="form-control">
                        </div>
                        <div class="form-group">
                            <textarea placeholder="Message" class="form-control" rows="15"></textarea>
                        </div>
                        <input type="button" value="Send Message" class="btn btn-primary">
                    </form>
                </div>
                <div class="col-sm-6">
                    <h3 class="block-title sub-title">
                        <span>Other Ways To Get In Touch</span>
                    </h3>
                    <p><abbr title="Phone">P</abbr>: 011/3210-112</p>
                    <p><abbr title="Fax">F</abbr>: 011/3210-112</p>
                    <p><abbr title="Email">E</abbr>: office@cubes.rs</p>
                    <p><abbr title="Address">A</abbr>: Bulevar Milutina Milankovića 181, 11000 Beograd</p>
                    
<!--                    <a href="https://maps.google.co.uk/maps?q=London&amp;ie=UTF8&amp;hq=&amp;hnear=London,+United+Kingdom&amp;gl=uk&amp;t=m&amp;ll=51.510238,-0.127029&amp;spn=0.042735,0.102654&amp;z=12&amp;">
                        <img class="img-polaroid" alt="Location map" src="/img/misc/map.png">
                    </a>-->

                    <div id="map" style="width:100%; height: 300px"></div>
                    
                    <script>
                        var map;
                        
                        function initMap() {
                            var myLatLng = {lat: 44.831213, lng: 20.410245};

                            map = new google.maps.Map(document.getElementById('map'), {
                                center: myLatLng,
                                zoom: 15
                            });
                            
                            marker = new google.maps.Marker({
                                position: myLatLng,
                                dragable: true,
                                map: map,
                                animation: google.maps.Animation.DROP,
                                title: 'Cubes School'
                            });
                            
                            marker.addListener('click', toggleBounce);
                        }
                        
                        function toggleBounce() {
                            if (marker.getAnimation() !== null) {
                                marker.setAnimation(null);
                            }
                            else {
                                marker.setAnimation(google.maps.Animation.BOUNCE);
                            }
                        }
                    </script>

                    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCl63DjLjiuUgfMShPAK0Jy5peunCa9NZ4&callback=initMap"
                            async defer>
                    </script>
                </div>
               
            </div>
        </div>
    </div>
</div>